Add init command
scm-manager/integration-test-runner pull request #4
Opened 2021-05-04 11:54 UTC by Pilopa

## Proposed changes

Create and document a new initialization command to be used by plugin developers to set up a plugin for development of bdd e2e tests.

### Your checklist for this pull request

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

**Contributor**:
- [ ] PR is well described and the description can be used as a commit message on squash
- [ ] Related issues linked to PR if existing and labels set
- [ ] Target branch is not master (in most cases develop should bet the target of choice) 
- [ ] Code does not conflict with target branch
- [ ] New code is covered with unit tests
- [ ] New ui components are tested inside the storybook (module ui-components only) 
- [ ] [Changelog entry file](https://github.com/scm-manager/changelog#changelog-entry-files) created in `gradle/changelog` or CHANGELOG.md is updated for plugins
- [ ] Documentation updated (only necessary for new features or changed behaviour)

**Reviewer**:
- [ ] The clean code principles are respected ([CleanCode](https://clean-code-developer.com/virtues/))
- [ ] All new code/logic is implemented on the right spot / "Should this be done here?"
- [ ] UI changes fits into the layout
- [ ] The UI views / components are responsive (mobile views)
- [ ] Correct translations are available

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

2021-05-06 08:05 UTC, eheimbuch commented
Doesn't work as expected. I checkout an SCM-Manager Plugin, added the dev dependency and ran the init command as the Readme told me. Now i get following error when i run `yarn run e2e`.

```
▶ yarn run e2e
yarn run v1.22.5
$ integration-test-runner run -u scmadmin -p scmadmin -O ../../../build/target/ -d ./src/test/e2e
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'lru-cache'
Require stack:
- /home/edi/Projects/integration-test-runner/node_modules/semver/classes/range.js
- /home/edi/Projects/integration-test-runner/node_modules/semver/classes/comparator.js
- /home/edi/Projects/integration-test-runner/node_modules/semver/index.js
- /home/edi/Projects/integration-test-runner/src/collect-releases.js
- /home/edi/Projects/integration-test-runner/cmds/collect.js
- /home/edi/Projects/integration-test-runner/node_modules/yargs/build/index.cjs
- /home/edi/Projects/integration-test-runner/node_modules/yargs/yargs
- /home/edi/Projects/integration-test-runner/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/edi/Projects/integration-test-runner/node_modules/semver/classes/range.js:187:13)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/edi/Projects/integration-test-runner/node_modules/semver/classes/range.js',
    '/home/edi/Projects/integration-test-runner/node_modules/semver/classes/comparator.js',
    '/home/edi/Projects/integration-test-runner/node_modules/semver/index.js',
    '/home/edi/Projects/integration-test-runner/src/collect-releases.js',
    '/home/edi/Projects/integration-test-runner/cmds/collect.js',
    '/home/edi/Projects/integration-test-runner/node_modules/yargs/build/index.cjs',
    '/home/edi/Projects/integration-test-runner/node_modules/yargs/yargs',
    '/home/edi/Projects/integration-test-runner/cli.js'
  ]
}
```

2021-05-06 08:09 UTC, eheimbuch requested changes

2021-05-06 08:09 UTC, eheimbuch commented on cmds/init.js
> +        "integration-test-runner run -u scmadmin -p scmadmin -O ../../../build/target/ -d ./src/test/e2e";
Is this path really correct? Why `../../../build/target/`? Doesn't this write the results outside of my plugin repository?

2021-05-07 07:27 UTC, Pilopa commented on cmds/init.js
> +        "integration-test-runner run -u scmadmin -p scmadmin -O ../../../build/target/ -d ./src/test/e2e";
That is actually "caused" by how cypress handles this configuration. The path is relative to the e2e directory.

2021-05-07 07:31 UTC, Pilopa commented
Unfortunately, putting the dependency into the `package.json` AND using `yarn link` seems to cause problems. Thats why I tested with `yarn link` but without putting it into the `package.json`. We should retest the workflow outlined in the readme once we published a version to `npmjs` that we can actually install.

2021-05-10 09:44 UTC, merged